extends:
  - stylelint-config-sugarss-recommended
ignoreFiles:
  - .nuxt/**/*
  - node_modules/**/*
plugins:
  - stylelint-order
rules:
  font-family-name-quotes: always-where-recommended # Font名のクォーテーションを省略する
  function-url-quotes: never # url()などの引数ではクォーテーションを省略する
  number-leading-zero: never # 1未満の場合は0を省略する
  order/properties-alphabetical-order: true # プロパティをアルファベット順に並べる
