extends:
  - stylelint-config-sugarss-recommended
ignoreFiles:
  - .nuxt/**/*
  - node_modules/**/*
plugins:
  - stylelint-order
  - stylelint-rscss
rules:
  font-family-name-quotes: always-where-recommended # Font名のクォーテーションを省略する
  function-url-quotes: never # url()などの引数ではクォーテーションを省略する
  number-leading-zero: never # 1未満の場合は0を省略する
  order/properties-alphabetical-order: true # プロパティをアルファベット順に並べる
  rscss/class-format: true # RSCSSのクラスフォーマットを強制する
  rscss/no-descendant-combinator: true # 子セレクタの指定に > を強制する
